# Generated by Django 5.1.3 on 2024-11-27 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Árbitro')),
                ('experiencia', models.PositiveIntegerField(help_text='Anos de experiência', verbose_name='Experiência')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('frase_efeito', models.CharField(max_length=100, verbose_name='Frase de Efeito')),
                ('qtd_jogadores', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Jogador')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('posicao', models.CharField(max_length=50, verbose_name='Posição')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='cadastros.time', verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('esporte', models.CharField(max_length=50, verbose_name='Esporte')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('times', models.ManyToManyField(related_name='eventos', to='cadastros.time', verbose_name='Times Participantes')),
            ],
        ),
    ]
