# Generated by Django 5.1.3 on 2024-11-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitro',
            options={'ordering': ['nome'], 'verbose_name': 'Árbitro', 'verbose_name_plural': 'Árbitros'},
        ),
        migrations.AlterModelOptions(
            name='jogador',
            options={'ordering': ['nome'], 'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['nome'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.RemoveField(
            model_name='time',
            name='frase de efeito',
        ),
        migrations.AddField(
            model_name='arbitro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='[default: timezone.now] >>> ', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arbitro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='10:20', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='time',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='10:20', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='frase_efeito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frase de Efeito'),
        ),
        migrations.AddField(
            model_name='time',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='experiencia',
            field=models.PositiveIntegerField(help_text='Anos de experiência', verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Árbitro'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='idade',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(max_length=50, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='cadastros.time', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='qtd_jogadores',
            field=models.PositiveIntegerField(verbose_name='Quantidade de Jogadores'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('esporte', models.CharField(max_length=50, verbose_name='Esporte')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('times', models.ManyToManyField(related_name='eventos', to='cadastros.time', verbose_name='Times Participantes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data'],
            },
        ),
    ]
