# Generated by Django 5.1.3 on 2024-11-27 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='evento',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='evento',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Atualização'),
        ),
    ]
