# Generated by Django 5.1.3 on 2024-11-26 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_arbitro_options_alter_jogador_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={},
        ),
        migrations.AlterField(
            model_name='time',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='time',
            name='frase_efeito',
            field=models.CharField(max_length=100, verbose_name='Frase de Efeito'),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='qtd_jogadores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
