# Generated by Django 5.1.3 on 2024-11-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_remove_time_created_at_remove_time_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitro',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='arbitro',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='updated_at',
        ),
    ]
