# Generated by Django 5.1.3 on 2024-11-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_arbitro_created_at_remove_arbitro_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jogador',
            options={},
        ),
    ]
